#!/bin/sh

if [ $# == 0 ] 
then
    cat <<EOF
Use: testa COMPILEDFILE.s
EOF
    exit 1
fi

TESTA=/tmp/testa$USER.s

rm $TESTA 2>/dev/null
if [ -f $1 ]
then 
cat runtime.s $1 |\
 awk '{if (/not/&&!/^ +not/) {gsub(/not/,"_not"); print} else print}' > $TESTA\
 && spim -file $TESTA
else
 echo No file $1
 exit 1
fi
